# Generated by Django 4.2.5 on 2023-09-28 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='Category',
            new_name='category',
        ),
    ]
